### ISSUE TITLE
no build

### ISSUE THREAD

**Issue by wuvinotre** [MericcaN41/discordjs-v14-template-ts#5]
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/Users/vuinishiusu/dev/bot/mini-pilar/build/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by mashwishi** [comment]
up

**Comment by matsyui** [comment]
@MericcaN41 i have already pushed the solution for this at https://github.com/MericcaN41/discordjs-v14-template-ts/pull/6/commits/6b40603ee49df9924dcb7b5257f43ade5c102205.

@wuvinotre hope this helps you:

## Installation, Build and Run
1) Clone the repository then create a file named `.env` and fill it out accordingly
```js
TOKEN=YOURTOKENHERE
CLIENT_ID=BOTS CLIENT ID
PREFIX=!
MONGO_URI=YOUR MONGO CONNECTION STRING
MONGO_DATABASE_NAME=YOUR DATABASE NAME
```

Build the project using the typescript module and start the bot using the `npm start` command
2) Install typescript, To install TypeScript, you can run the following command in your terminal, This will install the latest version of TypeScript globally on your computer. (You can skip this if you already have typescript installed)
  ```ts
  npm install -g typescript
  ```
3) Compile your TypeScript code to JavaScript by running the following command:
```js
tsc
```
4) Once the build is complete it will generated a folder named `build` that contains compiled version of your ts code to js. You can run the following command in your terminal to run the project:
```js
npm start
```

**Comment by MericcaN41** [comment]
Thanks for the help @mashwishi, merging now.

**Comment by wuvinotre** [comment]
My mistake, I didn't realize I should have compiled from TS to JS, thanks for the help @mashwishi
